#!/bin/sh
#
# @name Gazebo gs001
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=gs001}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_BAROSIM 1

param set-default SENS_EN_MAGSIM 1
param set-default SYS_HAS_MAG 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.09
param set-default CA_ROTOR0_PY 0.12
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.09
param set-default CA_ROTOR1_PY -0.12
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.09
param set-default CA_ROTOR2_PY -0.12
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.09
param set-default CA_ROTOR3_PY 0.12
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.20
param set-default NAV_DLL_ACT 0
param set-default COM_OF_LOSS_T 60.0

param set-default SYS_HAS_GPS 1
param set-default SENS_EN_GPSSIM 1
param set-default EKF2_HGT_REF 1 # 0 = baro, 1 = GPS
param set-default COM_ARM_WO_GPS 1

param set-default FD_FAIL_P 180
param set-default FD_FAIL_R 180


param set-default SENS_BOARD_X_OFF -90
param set-default SENS_BOARD_Z_OFF 180


param set-default MC_PITCHRATE_P 0.05
param set-default MC_PITCHRATE_I 0.025
param set-default MC_PITCHRATE_D 0.0005
param set-default MC_PITCHRATE_K 1.0

param set-default MC_ROLLRATE_P 0.05
param set-default MC_ROLLRATE_I 0.025
param set-default MC_ROLLRATE_D 0.0005
param set-default MC_ROLLRATE_K 1.0

param set-default MC_YAWRATE_P 0.35

param set-default MC_ROLL_P 4.0
param set-default MC_PITCH_P 4.0